export { ANALYSIS_MAX_RANGE_MS, DECISIONS_ROW_CAP, DEFAULT_LIMIT, MAX_LIMIT, MS_PER_DAY, STRATEGY_STATUS_ACTIVE } from './analysisConsts.js';
export {
    FUNNEL_MAINTENANCE_MARGIN_RATE,
    FUNNEL_MAX_LEVERAGE,
    FUNNEL_UTC_DATE_REGEX,
    MIN_CLOSED_TRADES_FOR_EDGE_VERDICT,
    MIN_TRADING_DAYS_FOR_EDGE_VERDICT,
    REGIME_BUCKET_MIN_N,
    BTC_REGIME_PARTITION_PCT,
    MISS_DISTANCE_BUCKET_EDGES,
} from './analysisFunnelConsts.js';
export { SYMBOL_REGEX, SYMBOL_MAX_LENGTH } from '@bot/shared';
