export enum RejectReasonEnum {
    MAX_POSITIONS_REACHED = 'max_positions_reached',
    BTC_CORRELATED_NOT_BEST_CANDIDATE = 'btc_correlated_not_best_candidate',
    BTC_CORRELATED_SLOT_TAKEN = 'btc_correlated_slot_taken',
    NO_ELIGIBLE_SLOT = 'no_eligible_slot',
    MARKET_STRESS = 'market_stress',
    OI_UNAVAILABLE = 'oi_unavailable',
    SPREAD_TOO_WIDE = 'spread_too_wide',
    BELOW_UNIVERSE_FLOOR = 'below_universe_floor',
    FUNDING_SUPPRESSED = 'funding_suppressed',
    COOLDOWN_ACTIVE = 'cooldown_active',
    DAILY_LOSS_LIMIT = 'daily_loss_limit',
    WEEKLY_LOSS_LIMIT = 'weekly_loss_limit',
    CONSECUTIVE_LOSS_HALT = 'consecutive_loss_halt',
    MAX_TRADES_PER_SYMBOL_PER_DAY = 'max_trades_per_symbol_per_day',
    MAX_TRADES_PER_BAR_UNIVERSE = 'max_trades_per_bar_universe',
    SAME_DIRECTION_EXPOSURE_CAP = 'same_direction_exposure_cap',
    EXPOSURE_CAP_PER_COIN = 'exposure_cap_per_coin',
    TIME_STOP_MISSING_OR_INVALID = 'time_stop_missing_or_invalid',
    SL_OUTSIDE_LIQUIDATION = 'sl_outside_liquidation',
    TIER3_NOT_VALIDATED = 'tier3_not_validated',
    MODEL_DIVERGENCE_HALT = 'model_divergence_halt',
    GLOBAL_HALT = 'global_halt',
    RECONCILING_HOLD = 'reconciling_hold',
    FOREIGN_POSITION_HOLD = 'foreign_position_hold',
    RECOVERY_IN_PROGRESS = 'recovery_in_progress',
}
